# Generated by Django 4.2.3 on 2023-09-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('registration_date', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('language', models.CharField(max_length=64)),
                ('current_job', models.CharField(default='', max_length=64)),
                ('job_title', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='job_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_created=True)),
                ('pay', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('job_offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job_offers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('job_offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job_offers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
