# Generated by Django 4.2.3 on 2023-09-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_data_alter_applications_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='job_offers',
            name='language',
        ),
        migrations.AddField(
            model_name='job_offers',
            name='title',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_offers',
            name='languages',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
            preserve_default=False,
        ),
    ]
