# Generated by Django 4.2.3 on 2023-09-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_languages_remove_job_offers_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_offers',
            name='part_time',
            field=models.BooleanField(default=False),
        ),
    ]
