# Generated by Django 4.2.3 on 2023-09-13 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_job_offers_part_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='phone_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='job_offers',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='contactRequests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=512)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
