# Generated by Django 4.2.3 on 2023-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_data_phone_number_alter_job_offers_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequests',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contactrequests',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequests',
            name='first_name',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequests',
            name='last_name',
            field=models.TextField(default=' ', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequests',
            name='phone_number',
            field=models.TextField(default=' ', max_length=32),
            preserve_default=False,
        ),
    ]
