# Generated by Django 4.2.3 on 2023-09-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_contactrequests_user_id_contactrequests_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorites',
        ),
    ]
